### ISSUE TITLE
PHP Fatal Error in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99

### ISSUE THREAD

**Issue by robertfausk** [knutschsoft/swapp#35]
## Error in swapp

**PHP Fatal Error** in **vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99**
Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\Component\HttpKernel\Kernel::terminate() must be an instance of Symfony\Component\HttpFoundation\Request, instance of React\Http\Request given, called in /home/robert/workspace/swapp/bin/react.php on line 40 in /home/robert/workspace/swapp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:130
Stack trace:
#0 /home/robert/workspace/swapp/bin/react.php(40): Symfony\Component\HttpKernel\Kernel->terminate(Object(React\Http\Request), Object(React\Http\Response))
#1 [internal function]: {closure}(Object(React\Http\Request), Object(React\Http\Response))
#2 /home/robert/workspace/swapp/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#3 /home/robert/workspace/swapp/vendor/react/http/src/Server.php(63): Evenement\EventEmitter->emit('request', Array)
#4 /home/robert/workspace/swapp/vendor/react/http/src/Server...

[View on Bugsnag](https://bugsnag.com/knutschsoft/swapp/errors/57923f4fe8a4560f5236b0d5?event_id=57923f4fd249bbc75abec7e4)
## Stacktrace

```
vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:99 - [unknown]
```

[View full stacktrace](https://bugsnag.com/knutschsoft/swapp/errors/57923f4fe8a4560f5236b0d5?event_id=57923f4fd249bbc75abec7e4)

**Comment by robertfausk** [comment]
not relevant
